GET http://localhost:5237/swagger

GET https://localhost:5237/swagger

POST https://localhost:5237/swagger
Content-Type: application/json

{
    "name": "Shoes",
    "description": "Running Shoes",
    "brand": "Nike",
    "price": 109.99
}